use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

// ── Types ─────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alias {
    pub command: String,
    pub category: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AliasStore {
    pub aliases: HashMap<String, Alias>,
}

// ── Manager ───────────────────────────────────────────────────────────────────

pub struct AliasManager {
    store: AliasStore,
    path: PathBuf,
}

impl AliasManager {
    fn aliases_path() -> PathBuf {
        crate::config::Config::config_dir().join("aliases.toml")
    }

    fn shell_path() -> PathBuf {
        crate::config::Config::config_dir().join("aliases.sh")
    }

    pub fn load() -> Result<Self> {
        let path = Self::aliases_path();
        let store = if path.exists() {
            let raw = std::fs::read_to_string(&path)
                .with_context(|| "Failed to read aliases.toml")?;
            toml::from_str(&raw).with_context(|| "Failed to parse aliases.toml")?
        } else {
            AliasStore::default()
        };

        Ok(Self { store, path })
    }

    pub fn save(&self) -> Result<()> {
        let dir = self.path.parent().unwrap();
        std::fs::create_dir_all(dir)?;
        let content = toml::to_string_pretty(&self.store)?;
        std::fs::write(&self.path, content)?;
        Ok(())
    }

    pub fn add(&mut self, key: &str, command: &str, category: Option<&str>) -> Result<()> {
        validate_alias_key(key)?;

        let alias = Alias {
            command: command.to_string(),
            category: category.map(|s| s.to_string()),
            created_at: Some(chrono::Local::now().to_rfc3339()),
        };

        self.store.aliases.insert(key.to_string(), alias);
        self.save()
    }

    pub fn remove(&mut self, key: &str) -> Result<()> {
        if self.store.aliases.remove(key).is_none() {
            anyhow::bail!("Alias '{key}' not found");
        }
        self.save()
    }

    pub fn list(&self, category: Option<&str>) {
        let reset = "\x1b[0m";
        let mut entries: Vec<(&String, &Alias)> = self.store.aliases.iter().collect();
        entries.sort_by_key(|(k, _)| k.as_str());

        if entries.is_empty() {
            println!("\x1b[90mNo aliases defined. Try: dashe alias add gs \"git status\"\x1b[0m");
            return;
        }

        // Group by category
        let filtered: Vec<_> = if let Some(cat) = category {
            entries
                .into_iter()
                .filter(|(_, a)| a.category.as_deref() == Some(cat))
                .collect()
        } else {
            entries
        };

        let mut current_cat = "";
        for (key, alias) in &filtered {
            let cat = alias.category.as_deref().unwrap_or("general");
            if cat != current_cat {
                println!("\n\x1b[96m{cat}\x1b[0m");
                println!("{}", "─".repeat(32));
                current_cat = cat;
            }
            println!(
                "  \x1b[92m{:<16}{reset}\x1b[90m→{reset}  \x1b[37m{}{reset}",
                key, alias.command
            );
        }
        println!();
    }

    pub fn export(&self, path: &str) -> Result<()> {
        let content = toml::to_string_pretty(&self.store)?;
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn import(&mut self, path: &str) -> Result<usize> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("Cannot read file: {path}"))?;
        let imported: AliasStore =
            toml::from_str(&raw).with_context(|| "Invalid alias file format")?;

        let count = imported.aliases.len();
        for (key, alias) in imported.aliases {
            self.store.aliases.insert(key, alias);
        }
        self.save()?;
        Ok(count)
    }

    /// Write a bash-sourceable file with all aliases
    pub fn write_shell_file(&self) -> Result<()> {
        let path = Self::shell_path();
        let dir = path.parent().unwrap();
        std::fs::create_dir_all(dir)?;

        let mut lines = vec![
            "# Generated by Dashe — do not edit manually".to_string(),
            "# Source this file in ~/.bashrc:".to_string(),
            "#   source ~/.config/dashe/aliases.sh".to_string(),
            String::new(),
        ];

        let mut entries: Vec<(&String, &Alias)> = self.store.aliases.iter().collect();
        entries.sort_by_key(|(k, _)| k.as_str());

        for (key, alias) in &entries {
            let cat = alias.category.as_deref().unwrap_or("general");
            lines.push(format!("# [{cat}]"));
            lines.push(format!("alias {}='{}'", key, alias.command.replace('\'', "'\\''")));
        }

        std::fs::write(&path, lines.join("\n") + "\n")?;
        Ok(())
    }
}

fn validate_alias_key(key: &str) -> Result<()> {
    if key.is_empty() {
        anyhow::bail!("Alias key cannot be empty");
    }
    if key.contains(' ') || key.contains('/') {
        anyhow::bail!("Alias key cannot contain spaces or '/'");
    }
    Ok(())
}
